# Generated by Django 3.2.6 on 2021-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Rev', 'Rev'), ('Ms', 'Ms'), ('Princess', 'Princess'), ('Prince', 'Prince')], max_length=15),
        ),
    ]
