# Generated by Django 3.2.6 on 2021-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Prince', 'Prince'), ('Princess', 'Princess'), ('Ms', 'Ms'), ('Mr', 'Mr'), ('Rev', 'Rev'), ('Dr', 'Dr')], max_length=15),
        ),
    ]
