# Generated by Django 3.2.6 on 2021-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Prince', 'Prince'), ('Princess', 'Princess'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Dr', 'Dr'), ('Rev', 'Rev'), ('Ms', 'Ms')], max_length=15),
        ),
    ]
