# Generated by Django 3.2.9 on 2021-11-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='featured',
        ),
    ]
