# Generated by Django 3.2.6 on 2021-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entres', 'entres'), ('treats', 'treats'), ('drink', 'drinks'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
