# Generated by Django 4.0.1 on 2022-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drink', 'drinks'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
