# Generated by Django 4.0.1 on 2022-04-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_name_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('treats', 'treats'), ('appetizers', 'appetizers'), ('drink', 'drinks')], max_length=60),
        ),
    ]
