# Generated by Django 4.0 on 2021-12-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Princess', 'Princess'), ('Mr', 'Mr'), ('Rev', 'Rev'), ('Mrs', 'Mrs'), ('Prince', 'Prince'), ('Ms', 'Ms')], max_length=15),
        ),
    ]
