# Generated by Django 3.2.6 on 2022-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Prince', 'Prince'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Rev', 'Rev'), ('Princess', 'Princess')], max_length=15),
        ),
    ]
