# Generated by Django 3.2.6 on 2022-07-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Prince', 'Prince'), ('Ms', 'Ms'), ('Rev', 'Rev'), ('Mrs', 'Mrs'), ('Princess', 'Princess'), ('Dr', 'Dr')], max_length=15),
        ),
    ]
